---
- name: Set variables
  ansible.builtin.set_fact:
    path: "{{ ansible_env.PATH }}:/usr/local/bin"
    r_libs: "{{ ansible_env.HOME }}/.clir/r/library"
    clir: "{{ ansible_env.HOME }}/.clir/bin/clir"
    install_clir_sh: /tmp/install_clir.sh

- name: Check R command
  environment:
    PATH: "{{ path }}"
  ansible.builtin.shell: |
    R --version
  changed_when: false
  failed_when: false

- name: Download the installer of clir
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/dceoy/clir/master/install_clir.sh
    dest: "{{ install_clir_sh }}"

- name: Install or update clir
  environment:
    PATH: "{{ path }}"
    R_LIBS_USER: "{{ r_libs }}"
  ansible.builtin.shell: |
    bash {{ install_clir_sh }}
  changed_when: true
  notify: Notify updates of R via Slack

- name: Remove the installer
  ansible.builtin.file:
    path: "{{ install_clir_sh }}"
    state: absent

- name: Set cran repositories
  when:
    - r_repos is defined
    - r_repos.cran is defined
  environment:
    PATH: "{{ path }}"
    R_LIBS_USER: "{{ r_libs }}"
  ansible.builtin.shell: |
    {{ clir }} cran {{ item }}
  loop: "{{ r_repos.cran }}"
  changed_when: true
  notify: Notify updates of R via Slack

- name: Set drat repositories
  when:
    - r_repos is defined
    - r_repos.drat is defined
  environment:
    PATH: "{{ path }}"
    R_LIBS_USER: "{{ r_libs }}"
  ansible.builtin.shell: |
    {{ clir }} drat {{ item }}
  loop: "{{ r_repos.drat }}"
  changed_when: true
  notify: Notify updates of R via Slack

- name: Install and update cran packages
  when:
    - r_repos is defined
    - r_repos.cran is defined
    - r_packages is defined
    - r_packages.cran is defined
  environment:
    PATH: "{{ path }}"
    R_LIBS_USER: "{{ r_libs }}"
  ansible.builtin.shell: |
    {{ clir }} install --devt=cran --quiet {{ item }}
  loop: "{{ r_packages.cran }}"
  changed_when: true
  failed_when: false
  notify: Notify updates of R via Slack

- name: Install and update drat packages
  when:
    - r_repos is defined
    - r_repos.drat is defined
    - r_packages is defined
    - r_packages.drat is defined
  environment:
    PATH: "{{ path }}"
    R_LIBS_USER: "{{ r_libs }}"
  ansible.builtin.shell: |
    {{ clir }} install --devt=cran --quiet {{ item }}
  loop: "{{ r_packages.drat }}"
  changed_when: true
  failed_when: false
  notify: Notify updates of R via Slack

- name: Install and update github packages
  when:
    - r_packages is defined
    - r_packages.github is defined
  environment:
    PATH: "{{ path }}"
    R_LIBS_USER: "{{ r_libs }}"
  ansible.builtin.shell: |
    {{ clir }} install --devt=github --quiet {{ item }}
  loop: "{{ r_packages.github }}"
  changed_when: true
  failed_when: false
  notify: Notify updates of R via Slack

- name: Install and update bioconductor packages
  when:
    - r_packages is defined
    - r_packages.bioconductor is defined
  environment:
    PATH: "{{ path }}"
    R_LIBS_USER: "{{ r_libs }}"
  ansible.builtin.shell: |
    {{ clir }} install --devt=bioc --quiet {{ item }}
  loop: "{{ r_packages.bioconductor }}"
  changed_when: true
  failed_when: false
  notify: Notify updates of R via Slack
