#!/usr/bin/env Rscript

.First <- function() {
  options(repos = c(CRAN = 'https://cran.rstudio.com/'),
          browserNLdisabled = TRUE,
          deparse.max.lines = 2)
}

.libPaths(c(paste0(Sys.getenv('HOME'), '/.clir/r/library')))

if(interactive()) {
  suppressMessages({
    n <- sapply(c('dbplyr', 'doParallel', 'foreach', 'tidyverse'),
                require,
                character.only = TRUE)
  })
}
