---
npm_packages:
  - ajv-cli
  - bats
  - eslint
  - eslint-config-airbnb
  - eslint-plugin-import
  - eslint-plugin-toml
  - htmlhint
  - markdownlint-cli2
  - prettier
  - pnpm
  - puppeteer
  - stylelint
  - stylelint-config-standard
  - typescript
  - wscat
