---
npm_packages:
  - "@biomejs/biome"
  - ajv-cli
  - bats
  - htmlhint
  - markdownlint-cli2
  - prettier
  - pnpm
  - puppeteer
  - stylelint
  - stylelint-config-standard
  - typescript
  - wscat
