---
- name: Mount external devices
  when:
    - external_storages is defined
    - inventory_hostname == item.host
  become: true
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    state: "{{ item.state }}"
  loop: "{{ external_storages }}"
  failed_when: false
  notify:
    - Notify updates of the external devices via Slack
