---
- name: Set proxy at /etc/environment
  when: http_proxy is defined or https_proxy is defined
  become: true
  ansible.builtin.blockinfile:
    dest: /etc/environment
    state: present
    block: |
      HTTP_PROXY={{ http_proxy }}
      HTTPS_PROXY={{ https_proxy }}
      NO_PROXY={{ no_proxy }}
      http_proxy={{ http_proxy }}
      https_proxy={{ https_proxy }}
      no_proxy={{ no_proxy }}
  notify: Notify updates of the system via Slack

- name: Set proxy at /etc/yum.conf
  when: http_proxy is defined or https_proxy is defined
  become: true
  ansible.builtin.blockinfile:
    dest: /etc/yum.conf
    state: present
    block: |
      proxy={{ http_proxy }}
  notify: Notify updates of the system via Slack

- name: Write %wheel in /etc/sudoers
  when:
    - enable_nopass_sudo is defined
    - enable_nopass_sudo
  become: true
  ansible.builtin.blockinfile:
    dest: /etc/sudoers
    state: present
    block: |
      %wheel  ALL=(ALL)       NOPASSWD: ALL
    validate: 'visudo -cf %s'
  notify: Notify updates of the system via Slack

- name: Upgrade all packages
  become: true
  ansible.builtin.yum:
    update_cache: yes
    name: '*'
    state: latest
  notify: Notify updates of the system via Slack

- name: Install packages
  when: yum_packages is defined
  become: true
  ansible.builtin.yum:
    name: "{{ yum_packages }}"
    state: latest
  failed_when: false
  notify: Notify updates of the system via Slack

- name: Set users
  when: users is defined
  become: true
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: yes
  loop: "{{ users }}"
  notify: Notify updates of the system via Slack
