---
- name: Set up development servers with root
  hosts:
    - linux
  gather_facts: true
  become: true
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"
  roles:
    - role: fedora
      when: ansible_facts['distribution'] == 'Fedora'
      tags: [os, fedora]
    - role: centos
      when: ansible_facts['distribution'] == 'CentOS'
      tags: [os, centos]
    - role: ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      tags: [os, ubuntu]

- name: Set up development servers
  hosts:
    - linux
    - macos
  gather_facts: true
  become: "{{ ansible_facts['distribution'] != 'MacOSX' }}"
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"
  roles:
    - role: macos
      when: ansible_facts['distribution'] == 'MacOSX'
      tags: [os, macos]
    - role: cli
      tags: [tools, cli]
    - role: vim
      tags: [tools, vim, editor]
    - role: python
      tags: [languages, python]
    - role: nodejs
      tags: [languages, nodejs, javascript]
    - role: ruby
      tags: [languages, ruby]
    - role: go
      tags: [languages, go, golang]
    - role: r
      tags: [languages, r, statistics]
  post_tasks:
    - name: Display completion message
      ansible.builtin.debug:
        msg: "Development server setup completed successfully!"
      run_once: true
