---
- name: Install and update packages
  when: pip_packages is defined
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    state: latest
    break_system_packages: true
  failed_when: false
  notify: Notify updates of Python via Slack
