---
- name: Check NVIDIA drivers
  when: nvidia_installer is defined
  ansible.builtin.stat:
    path: /usr/bin/nvidia-smi
  register: nvidia_smi

- name: Install NVIDIA drivers
  when:
    - nvidia_installer is defined
    - not nvidia_smi.stat.exists
  become: true
  ansible.builtin.shell: |
    bash {{ nvidia_installer }} --dkms --silent
  changed_when: true
  notify: Notify updates of NVIDIA via Slack
