---
- name: Update macOS
  ansible.builtin.shell:
    cmd: >
      softwareupdate --install --all --agree-to-license --force
    executable: /bin/bash
  changed_when: true
  failed_when: false
  notify: Notify updates of the system via Slack

- name: Update homebrew and upgrade all packages
  become: false
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  notify: Notify updates of the system via Slack

- name: Install packages
  become: false
  when: brew_packages is defined
  community.general.homebrew:
    name: "{{ brew_packages }}"
    state: latest
  notify: Notify updates of the system via Slack

- name: Install cask packages
  become: false
  when: brew_cask_packages is defined
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
  failed_when: false
  loop: "{{ brew_cask_packages }}"
  notify: Notify updates of the system via Slack
