---
- name: Update macOS
  ansible.builtin.command:
    argv:
      - softwareupdate
      - --install
      - --all
      - --agree-to-license
      - --force
  changed_when: true
  failed_when: false
  notify: Notify updates of the system via Slack

- name: Update homebrew and upgrade all packages
  become: false
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  notify: Notify updates of the system via Slack

- name: Install packages
  become: false
  when: macos_brew_packages is defined
  community.general.homebrew:
    name: "{{ macos_brew_packages }}"
    state: latest  # noqa: package-latest
  notify: Notify updates of the system via Slack

- name: Install cask packages
  become: false
  when: macos_brew_cask_packages is defined
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest  # noqa: package-latest
  failed_when: false
  loop: "{{ macos_brew_cask_packages }}"
  notify: Notify updates of the system via Slack
