---
pip_packages:
  - alpha_vantage
  - ansible-lint
  - apache-airflow
  - apache-libcloud
  - aws-cdk-lib
  - aws-lambda-powertools
  - bash_kernel
  - biopython
  - beautifulsoup4
  - black
  - bokeh
  - boto3
  - bottle
  - bayesian-optimization
  - catboost
  - cfn-lint
  - colored-traceback
  - coloredlogs
  - cookiecutter
  - csvkit
  - cutadapt
  - cython
  - docker
  - docopt
  - fabric
  - fastapi
  - git-remote-codecommit
  - greenlet
  - grip
  - h5py
  - hiredis
  - holoviews
  - hyperopt
  - injector
  - interpret
  - ipykernel
  - ipython
  - jsonschema
  - jupyter
  - keras
  - langchain
  - lifelines
  - lightgbm
  - llama-cpp-python
  - llama-index
  - luigi
  - magika
  - matplotlib
  - marimo
  - mkl
  - mock
  - MonkeyType
  - mypy
  - notebook
  - numexpr
  - numpy
  - pandas
  - pandas-datareader
  - pandera
  - pillow
  - pipx
  - plotly
  - polars
  - pr-agent
  - pre-commit
  - prophet
  - psutil
  - psycopg2-binary
  - pubnub
  - plyvel
  - pydantic
  - pydot
  - pygam
  - pyinstaller
  - pymc
  - pynvim
  - pyopenssl
  - pypandoc
  - pypdf
  - pyright
  - pysam
  - pystan
  - pytest
  - pyyaml
  - redis
  - requests
  - requests_oauthlib
  - rpy2
  - ruff
  - sabr
  - scikit-learn
  - scipy
  - seaborn
  - selenium
  - setuptools
  - six
  - sklearn-pandas
  - sktime
  - sphinx
  - sqlmodel
  - statsmodels
  - streamlit
  - streamz
  - sympy
  - tensorflow
  - testfixtures
  - torch
  - torchvision
  - tornado
  - tox
  - tqdm
  - tryceratops
  - twine
  - ty
  - types-docopt
  - types-jsonschema
  - types-setuptools
  - umap-learn
  - uv
  - vulture
  - webtest
  - xgboost
  - xmltodict
  - yamllint
  - yq
