" vim-plug
" default plugin directory:
"   - Vim (Linux/macOS): '~/.vim/plugged'
"   - Vim (Windows): '~/vimfiles/plugged'
"   - Neovim (Linux/macOS/Windows): stdpath('data') . '/plugged'
call plug#begin()

" colorscheme
Plug 'cocopon/iceberg.vim'                    " bluish colorscheme for Vim and Neovim
" lint/fix
Plug 'dense-analysis/ale'                     " asynchronous linting/fixing for vim and neovim
" syntax not provided by Vim runtime
Plug 'chazmcgarvey/vim-mermaid'               " Mermaid syntax
Plug 'elixir-editors/vim-elixir'              " Elixir syntax and indentation
Plug 'pearofducks/ansible-vim'                " Ansible syntax support
Plug 'aliou/bats.vim'                         " Bats syntax
Plug 'prisma/vim-prisma'                      " Prisma schema syntax
" Copilot
Plug 'github/copilot.vim'                     " GitHub Copilot

call plug#end()
packadd! editorconfig                        " EditorConfig support bundled with Vim

" indentation fallback; filetype plugins and EditorConfig can override per buffer
set autoindent
set expandtab
set shiftwidth=2
set softtabstop=-1

" colorscheme
set termguicolors
set background=dark
colorscheme iceberg

" whitespace visibility
" Tabs are unusual but valid, trailing spaces should be removed, and U+3000
" spaces should normally be replaced with ASCII spaces. Leading spaces are
" ordinary indentation and intentionally left unmarked.
set list listchars=tab:>-,trail:_
hi SpecialKey ctermbg=NONE ctermfg=110 guibg=NONE guifg=#84a0c6
hi TrailingWhitespace ctermbg=NONE ctermfg=203 guibg=NONE guifg=#e27878
hi ZenkakuSpace cterm=underline ctermul=216 gui=underline guisp=#e2a478
function! s:HighlightWhitespace() abort
  if exists('w:trailing_whitespace_match')
    silent! call matchdelete(w:trailing_whitespace_match)
  endif
  if exists('w:zenkaku_space_match')
    silent! call matchdelete(w:zenkaku_space_match)
  endif
  let w:trailing_whitespace_match = matchadd('TrailingWhitespace', ' \+$', 20)
  let w:zenkaku_space_match = matchadd('ZenkakuSpace', '\%u3000', 20)
endfunction
augroup HighlightWhitespace
  autocmd!
  autocmd VimEnter,BufWinEnter,WinEnter * call <SID>HighlightWhitespace()
augroup END

" ALE
let g:ale_linters_explicit = 1
let g:ale_linters = {
\   'python': ['ruff', 'pyright'],
\   'javascript': ['eslint'],
\   'typescript': ['eslint'],
\   'css': ['stylelint'],
\   'scss': ['stylelint'],
\   'less': ['stylelint'],
\   'json': ['jq'],
\   'yaml': ['yamllint'],
\   'ansible': ['ansible-lint'],
\   'sh': ['shellcheck'],
\   'bash': ['shellcheck'],
\   'zsh': ['zsh'],
\   'r': ['lintr'],
\   'rmd': ['lintr'],
\   'ruby': ['rubocop'],
\   'go': ['golangci-lint'],
\   'sql': ['sqlfluff'],
\   'markdown': ['markdownlint'],
\   'html': ['htmlhint'],
\   'terraform': ['tflint'],
\}
let g:ale_fixers = {
\   'python': ['ruff_format'],
\   'javascript': ['prettier'],
\   'typescript': ['prettier'],
\   'css': ['prettier'],
\   'scss': ['prettier'],
\   'less': ['prettier'],
\   'json': ['prettier'],
\   'yaml': ['prettier'],
\   'markdown': ['prettier'],
\   'html': ['prettier'],
\   'sh': ['shfmt'],
\   'bash': ['shfmt'],
\   'r': ['styler'],
\   'rmd': ['styler'],
\   'ruby': ['rubocop'],
\   'go': ['gofmt'],
\   'sql': ['sqlfluff'],
\   'terraform': ['terraform'],
\}
let g:ale_python_pyright_config = {
\   'python': {
\     'analysis': {
\       'diagnosticSeverityOverrides': {
\         'reportPrivateUsage': 'none',
\       },
\     },
\   },
\}
let g:ale_python_ruff_options = '--extend-select=F,E,W,C90,I,N,UP,S,B,COM,C4,PT,Q,SIM,ARG,ERA,PD,PLC,PLR,PLE,PLW,TRY,FLY,NPY,PERF,FURB,RUF --ignore=S101,B008,A002,A004,COM812,PLC2701,TRY003'
let g:ale_yaml_yamllint_options = '-d "{extends: default, rules: {line-length: disable, truthy: disable}}"'
let g:ale_r_lintr_options = 'linters_with_defaults(object_usage_linter = NULL, quotes_linter = NULL, absolute_path_linter = NULL, object_name_linter = NULL, line_length_linter = line_length_linter(99))'
let g:ale_markdown_markdownlint_executable = 'markdownlint-cli2'
