" vim-plug
" default plugin directory:
"   - Vim (Linux/macOS): '~/.vim/plugged'
"   - Vim (Windows): '~/vimfiles/plugged'
"   - Neovim (Linux/macOS/Windows): stdpath('data') . '/plugged'
call plug#begin()

" colorscheme
Plug 'altercation/vim-colors-solarized'       " precision colorscheme for the vim text editor
" lint/fix
Plug 'dense-analysis/ale'                     " asynchronous linting/fixing for vim and neovim
" syntax not provided by Vim runtime
Plug 'chazmcgarvey/vim-mermaid'               " Mermaid syntax
Plug 'elixir-editors/vim-elixir'              " Elixir syntax and indentation
Plug 'pearofducks/ansible-vim'                " Ansible syntax support
Plug 'aliou/bats.vim'                         " Bats syntax
Plug 'prisma/vim-prisma'                      " Prisma schema syntax
" Copilot
Plug 'github/copilot.vim'                     " GitHub Copilot

call plug#end()
packadd! editorconfig                        " EditorConfig support bundled with Vim

" Solarized
set background=dark
let g:solarized_termcolors=256
let g:solarized_contrast='high'
let g:solarized_visibility='high'
colorscheme solarized

" whitespace visibility
set list listchars=trail:_
hi SpecialKey ctermbg=NONE ctermfg=009 guibg=NONE guifg=#dc322f
hi ZenkakuSpace ctermbg=117 guibg=#87d7ff
function! s:HighlightZenkakuSpace() abort
  if exists('w:zenkaku_space_match')
    silent! call matchdelete(w:zenkaku_space_match)
  endif
  let w:zenkaku_space_match = matchadd('ZenkakuSpace', '\%u3000')
endfunction
augroup HighlightWhitespace
  autocmd!
  autocmd VimEnter,BufWinEnter,WinEnter * call <SID>HighlightZenkakuSpace()
augroup END

" ALE
let g:ale_linters_explicit = 1
let g:ale_linters = {
\   'python': ['ruff', 'pyright'],
\   'javascript': ['eslint'],
\   'typescript': ['eslint'],
\   'css': ['stylelint'],
\   'scss': ['stylelint'],
\   'less': ['stylelint'],
\   'json': ['jq'],
\   'yaml': ['yamllint'],
\   'ansible': ['ansible-lint'],
\   'dockerfile': ['hadolint'],
\   'sh': ['shellcheck'],
\   'bash': ['shellcheck'],
\   'zsh': ['zsh'],
\   'r': ['lintr'],
\   'rmd': ['lintr'],
\   'ruby': ['rubocop'],
\   'go': ['golangci-lint'],
\   'sql': ['sqlfluff'],
\   'markdown': ['markdownlint'],
\   'html': ['htmlhint'],
\   'terraform': ['tflint'],
\}
let g:ale_fixers = {
\   'python': ['ruff_format'],
\   'javascript': ['prettier'],
\   'typescript': ['prettier'],
\   'css': ['prettier'],
\   'scss': ['prettier'],
\   'less': ['prettier'],
\   'json': ['prettier'],
\   'yaml': ['prettier'],
\   'markdown': ['prettier'],
\   'html': ['prettier'],
\   'sh': ['shfmt'],
\   'bash': ['shfmt'],
\   'r': ['styler'],
\   'rmd': ['styler'],
\   'ruby': ['rubocop'],
\   'go': ['gofmt'],
\   'sql': ['sqlfluff'],
\   'terraform': ['terraform'],
\}
let g:ale_markdown_markdownlint_executable = 'markdownlint-cli2'
