#!/usr/bin/env zsh

# ------------------------------
# General Settings
# ------------------------------

export EDITOR=vim
export KCODE=u
export AUTOFEATURE=true

bindkey -e
# bindkey -v

setopt no_beep
setopt auto_cd
setopt auto_pushd
setopt correct
setopt magic_equal_subst
setopt prompt_subst
setopt notify
setopt equals

### Complement ###
autoload -U compinit; compinit
setopt auto_list
setopt auto_menu
setopt list_packed
setopt list_types
bindkey '^[[Z' reverse-menu-complete
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

### Glob ###
setopt extended_glob
unsetopt caseglob

### History ###
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt bang_hist
setopt extended_history
setopt hist_ignore_dups
setopt share_history
setopt hist_reduce_blanks

autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey '^P' history-beginning-search-backward-end
bindkey '^N' history-beginning-search-forward-end

function history-all { history -E 1 }


# ------------------------------
# Look And Feel Settings
# ------------------------------

### Ls Color ###
export LSCOLORS=Exfxcxdxbxegedabagacad
export LS_COLORS='di=01;34:ln=01;35:so=01;32:ex=01;31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
export ZLS_COLORS="${LS_COLORS}"
export CLICOLOR=true
zstyle ':completion:*:default' list-colors "${(s.:.)LS_COLORS}"

### Prompt ###
autoload -U colors; colors

tmp_prompt="%{${fg[cyan]}%}%n%# %{${reset_color}%}"
tmp_prompt2="%{${fg[cyan]}%}%_> %{${reset_color}%}"
tmp_rprompt="%{${fg[green]}%}[%~]%{${reset_color}%}"
tmp_sprompt="%{${fg[yellow]}%}%r is correct? [Yes, No, Abort, Edit]:%{${reset_color}%}"

if [[ ${UID} -eq 0 ]]; then
  tmp_prompt="%B%U${tmp_prompt}%u%b"
  tmp_prompt2="%B%U${tmp_prompt2}%u%b"
  tmp_rprompt="%B%U${tmp_rprompt}%u%b"
  tmp_sprompt="%B%U${tmp_sprompt}%u%b"
fi

PROMPT="${tmp_prompt}"
PROMPT2="${tmp_prompt2}"
RPROMPT="${tmp_rprompt}"
SPROMPT="${tmp_sprompt}"

[[ -n "${REMOTEHOST}${SSH_CONNECTION}" ]] && PROMPT="%{${fg[white]}%}${HOST%%.*} ${PROMPT}"


# ------------------------------
# Other Settings
# ------------------------------

### Custom ###
export LC_ALL='en_US.UTF-8'
setopt nonomatch

case "${OSTYPE}" in
  darwin* )
    PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/findutils/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/grep/libexec/gnubin:${PATH}"
    MANPATH="/usr/local/opt/coreutils/libexec/gnuman:/usr/local/opt/findutils/libexec/gnuman:/usr/local/opt/gnu-sed/libexec/gnuman:/usr/local/opt/gnu-tar/libexec/gnuman:/usr/local/opt/grep/libexec/gnuman:${MANPATH}"
    alias tree='tree -N'
    alias brew-update-upgrade-cleanup='brew update && brew upgrade && brew cleanup'
    function restart-app {
      for a (${*}) killall ${a} && open -a ${a}
    }
    GCSDK_DIR='/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk' \
      && [[ -d "${GCSDK_DIR}" ]] \
      && source "${GCSDK_DIR}/path.zsh.inc" \
      && source "${GCSDK_DIR}/completion.zsh.inc"
    ;;
  linux* )
    :
    ;;
esac

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias zgrep='zgrep --color=auto'
alias v='vim'
alias vi='vi -u NONE --noplugin -N'
alias l='ls -CF'
alias ll='ls -lF'
alias lla='ls -lA'
alias llh='ls -lh'
alias less='less -iMRW'
alias diff='colordiff -u'
alias d='docker'
alias dbash='docker container run --rm -it --entrypoint=bash'
alias dcbash='docker-compose run --rm --entrypoint=bash'
alias dc='docker-compose'
alias drmc='docker container ps -aq | xargs docker container rm'
alias drmi='docker image ls | awk "/<none>/ { print \$3 }" | xargs docker image rm'
alias dnginx='docker container run --rm -p 80:80 -v ${PWD}:/var/www/html:ro -d dceoy/nginx-autoindex'
alias dcrmf='docker-compose stop && docker-compose rm -f'
alias rv='R --quiet --no-save --no-restore'
alias exec-ipynb='docker container run --rm --user $(id -u):$(id -g) -v ${PWD}:/wd --workdir /wd --entrypoint jupyter dceoy/pydata nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --execute --inplace --ExecutePreprocessor.kernel_name=python'
alias git-diff-csv='git diff --color-words="[^[:space:],]+"'

[[ -d "${HOME}/.rbenv" ]] \
  && export PATH="${HOME}/.rbenv/bin:${PATH}" \
  && eval "$(rbenv init -)"
[[ -d "${HOME}/.pyenv" ]] \
  && export PATH="${HOME}/.pyenv/bin:${PATH}" \
  && eval "$(pyenv init -)"
[[ -n ${commands[kubectl]} ]] && source <(kubectl completion zsh)
[[ -n "${UID}" ]] || export UID="$(id -u)"
[[ -n "${GID}" ]] || export GID="$(id -g)"
export R_LIBS_USER="${HOME}/.clir/r/library"
export GOPATH="${HOME}/.go"
export PATH="${HOME}/.vim/bin:${GOPATH}/bin:${PATH}:${HOME}/.clir/bin:${HOME}/.local/bin"

### Git ###
autoload -Uz vcs_info
zstyle ':vcs_info:*' formats '%b '
zstyle ':vcs_info:*' actionformats '%b|%a '
function precmd {
  psvar=()
  LANG=en_US.UTF-8 vcs_info
  [[ -n "${vcs_info_msg_0_}" ]] && psvar[1]="${vcs_info_msg_0_}"
}
RPROMPT="%1(v|%F{green}%1v%f|)${RPROMPT}"
