#!/usr/bin/env zsh

# ------------------------------
# General Settings
# ------------------------------

# Editor and Encoding
export EDITOR=vim
export LC_ALL='en_US.UTF-8'
export AUTOFEATURE=true

# Keybindings
bindkey -e  # Emacs-like keybindings
# Uncomment for Vi-like keybindings
# bindkey -v

# Zsh Options
setopt no_beep auto_cd auto_pushd correct magic_equal_subst prompt_subst notify equals

# Completion Settings
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
bindkey '^[[Z' reverse-menu-complete

setopt auto_list auto_menu list_packed list_types

# Glob Settings
setopt extended_glob
unsetopt caseglob

# ------------------------------
# History Settings
# ------------------------------

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

setopt bang_hist extended_history hist_ignore_dups share_history hist_reduce_blanks

# History Search with End Positioning
autoload -Uz history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end

bindkey '^P' history-beginning-search-backward-end
bindkey '^N' history-beginning-search-forward-end

# Function to display all history entries
function history-all { history -E 1 }

# ------------------------------
# Look And Feel Settings
# ------------------------------

# LS Colors (for `ls` and completion)
export LSCOLORS=Exfxcxdxbxegedabagacad  # macOS-specific format
export LS_COLORS='di=01;34:ln=01;35:so=01;32:ex=01;31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
export CLICOLOR=true

# Prompt Colors and Styles
autoload -Uz colors && colors

PROMPT="%{$fg[cyan]%}%n%# %{$reset_color%}"
PROMPT2="%{$fg[cyan]%}%_> %{$reset_color%}"
RPROMPT="%{$fg[green]%}[%~]%{$reset_color%}"
SPROMPT="%{$fg[yellow]%}%r is correct? [Yes, No, Abort, Edit]:%{$reset_color%}"

if [[ ${UID} -eq 0 ]]; then  # Root user prompt styling
  PROMPT="%B%U${PROMPT}%u%b"
  PROMPT2="%B%U${PROMPT2}%u%b"
  RPROMPT="%B%U${RPROMPT}%u%b"
  SPROMPT="%B%U${SPROMPT}%u%b"
fi

[[ -n "${REMOTEHOST}${SSH_CONNECTION}" ]] && PROMPT="%{$fg[white]%}${HOST%%.*} ${PROMPT}"

# ------------------------------
# Miscellaneous Settings
# ------------------------------

setopt nonomatch  # Prevent errors for unmatched globs

### Git ###
autoload -Uz vcs_info
zstyle ':vcs_info:*' formats '%b '
zstyle ':vcs_info:*' actionformats '%b|%a '
function precmd {
  psvar=()
  LANG=en_US.UTF-8 vcs_info
  if [[ -n "${vcs_info_msg_0_}" ]]; then
    psvar[1]="${vcs_info_msg_0_}"
  fi
}
RPROMPT="%1(v|%F{green}%1v%f|)${RPROMPT}"
