---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if Python 3 is installed
      ansible.builtin.command: python3 --version
      register: python_version
      changed_when: false
      failed_when: python_version.rc != 0

    - name: Check if pip is installed
      ansible.builtin.command: pip3 --version
      register: pip_version
      changed_when: false
      failed_when: pip_version.rc != 0

    - name: Check if pyenv is installed
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.pyenv"
      register: pyenv_stat
      failed_when: not pyenv_stat.stat.exists

    - name: Display versions
      ansible.builtin.debug:
        msg:
          - "Python: {{ python_version.stdout }}"
          - "Pip: {{ pip_version.stdout }}"
          - "Pyenv installed: {{ pyenv_stat.stat.exists }}"