---
- name: Put ~/.vimrc
  ansible.builtin.copy:
    src: vimrc
    dest: "{{ ansible_facts['env']['HOME'] }}/.vimrc"
    mode: "0644"
  notify: Notify updates of Vim via Slack

- name: Create a temporary file for the install-latest-vim installer
  ansible.builtin.tempfile:
    state: file
    suffix: .sh
  register: vim_installer

- name: Download install-latest-vim installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/dceoy/install-latest-vim/aae0875c9a5a9c34fabb36e303535a9fd07514f8/install_latest_vim.sh
    dest: "{{ vim_installer.path }}"
    mode: "0755"
    force: true

- name: Install or update Vim and Vim plugins
  ansible.builtin.command:
    argv:
      - "{{ vim_installer.path }}"
      - --lua
      - --vim-plug
  changed_when: true
  failed_when: false
  notify: Notify updates of Vim via Slack

- name: Remove install-latest-vim installer
  ansible.builtin.file:
    path: "{{ vim_installer.path }}"
    state: absent

- name: Add ~/.vim/bin to PATH
  ansible.builtin.blockinfile:
    create: true
    dest: "{{ ansible_facts['env']['HOME'] }}/.zprofile"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Vim tools"
    mode: "0644"
    state: present
    block: |
      export PATH="${HOME}/.vim/bin:${PATH}"
  notify: Notify updates of Vim via Slack
