---
- name: Put ~/.vimrc
  ansible.builtin.copy:
    src: vimrc
    dest: "{{ ansible_facts['env']['HOME'] }}/.vimrc"
    mode: "0644"
  notify: Notify updates of Vim via Slack

- name: Remove legacy install-latest-vim artifacts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_facts['env']['HOME'] }}/.vim/src/install-latest-vim"
    - "{{ ansible_facts['env']['HOME'] }}/.vim/src/install_latest_vim.sh"
  notify: Notify updates of Vim via Slack

- name: Download install-latest-vim installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/dceoy/install-latest-vim/aae0875c9a5a9c34fabb36e303535a9fd07514f8/install_latest_vim.sh
    dest: /tmp/install_latest_vim.sh
    mode: "0755"
    force: true

- name: Install or update Vim and Vim plugins
  ansible.builtin.command:
    argv:
      - /tmp/install_latest_vim.sh
      - --lua
      - --vim-plug
  changed_when: true
  failed_when: false
  notify: Notify updates of Vim via Slack

- name: Remove install-latest-vim installer
  ansible.builtin.file:
    path: /tmp/install_latest_vim.sh
    state: absent
